# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cp readme.md
        run: cp README.md docs/README.md ; cp design-patterns/README.md docs/arch/design_patterns.md
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          # CONFIG_FILE: folder/mkdocs.yml
          # EXTRA_PACKAGES: build-base
          # # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt
